server {
    listen 80;
    root /usr/share/nginx/html;

    location /api/employees/ {
        proxy_pass http://employees-service:8081/;
        proxy_cookie_path /auth /api/employees/auth;
    }

    location /api/tickets/ {
        proxy_pass http://ticket-service:8080/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
