apiVersion: v2
name: sys-called
description: Sistema de controle de chamados internos (ticket-service, employees-service e frontend) com Postgres e Kafka
type: application
version: 0.1.0
appVersion: "1.0.0"
